
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Mostafa Jubayer Khan  ## put your name
title: 'Data Analyst &amp; Machine Learning Enthusiast'  ## your title
location: Frederick , MD


## Social Profiles
facebook: http://www.facebook.com/jubayermustafa ## your facebook account url
twitter: http://www.twitter.com/MJKhan01  ## your twitter account url
linkedin: https://www.linkedin.com/in/mostafa-jubayer-khan/  ## your linkedin account url
github: https://github.com/mostafajubayerkhan  ## you dribbble account url
youtube: https://www.youtube.com/channel/UC1kipe4ux_hKxApqJXPQSKg?view_as=subscriber  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
